# Generated by Django 6.0.4 on 2026-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
