# Generated by Django 6.0.4 on 2026-05-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="bio",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="description",
            field=models.TextField(),
        ),
    ]
